### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by zslt64** [hisacro/Hexchat-Google-Translator-Plugin#1]
1. user translation could override channel translation, like someone speaking russian, in a korean channel. And all I want to translate to english.

2. when saying !!@nickname message - the @nickname part should be kept as is.

**Comment by hisacro** [comment]
1. I tried something similar with `/TR` `/TRA` in the past but that didn't auto detect properly.
[try this](https://github.com/hisacro/Hexchat-Google-Translator-Plugin/blob/master/google_translator.py#L95) I believe this should work for languages not using en fonts (to avoid ambiguity)

2. [user mention commit](https://github.com/hisacro/Hexchat-Google-Translator-Plugin/commit/6448516459eee90dbf0c38e7cfc1e9296be5a1ab)

**Comment by hisacro** [comment]
@zslt64 sanitized user mention, as '@' in output is pointless.

```
# input
!!@chair1234, hello
# output
chair1234, Hallo
```
